/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsrl_net_JavaPing */

#ifndef _Included_jsrl_net_JavaPing
#define _Included_jsrl_net_JavaPing
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: __javaping_singleton */
/* Inaccessible static: class_00024com_00024giti_00024cpof_00024admin_00024util_00024ping_00024JavaPing */
/*
 * Class:     jsrl_net_JavaPing
 * Method:    ping
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT jboolean JNICALL Java_jsrl_net_JavaPing_ping
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     jsrl_net_JavaPing
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsrl_net_JavaPing_end
  (JNIEnv *, jobject);

/*
 * Class:     jsrl_net_JavaPing
 * Method:    _pong
 * Signature: (ILcom/giti/cpof/admin/util/ping/PingResult;)Z
 */
JNIEXPORT jboolean JNICALL Java_jsrl_net_JavaPing__1pong
  (JNIEnv *, jobject, jint, jobject);


/*
 * Class:     jsrl_net_JavaPing
 * Method:    ping
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT jboolean JNICALL Java_jsrl_net_JavaPing__1pingpong
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jobject);

/*
 * Class:     jsrl_net_JavaPing
 * Method:    begin
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_jsrl_net_JavaPing_begin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
