/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsrl_sys_Keyboard */

#ifndef _Included_jsrl_sys_Keyboard
#define _Included_jsrl_sys_Keyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsrl_sys_Keyboard
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsrl_sys_Keyboard_start
  (JNIEnv *, jobject);

/*
 * Class:     jsrl_sys_Keyboard
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsrl_sys_Keyboard_stop
  (JNIEnv *, jobject);

/*
 * Class:     jsrl_sys_Keyboard
 * Method:    _registerHotKey
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsrl_sys_Keyboard__1registerHotKey
  (JNIEnv *, jobject, jint, jint, jboolean passthrough);

/*
 * Class:     jsrl_sys_Keyboard
 * Method:    _unregisterHotKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jsrl_sys_Keyboard__1unregisterHotKey
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
